
USE FGBDD
--Tabla proveedor
CREATE TABLE PROVEEDOR(
CLAVEPROV SMALLINT NOT NULL IDENTITY(1,1), 
NOMBRE VARCHAR(25) NOT NULL,
APELLIDOP VARCHAR(15) NOT NULL, 
APELLIDOM VARCHAR(15) NOT NULL,
NUMTEL BIGINT NOT NULL, 
CORREO VARCHAR(40) NOT NULL,
CONSTRAINT PK_PROV PRIMARY KEY(CLAVEPROV)
)

--Tabla Empleado
CREATE TABLE EMPLEADO(
CLAVEEMP SMALLINT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(25) NOT NULL,
APELLIDOP VARCHAR(15) NOT NULL, 
APELLIDOM VARCHAR(15) NOT NULL,
NUMTEL BIGINT NOT NULL, 
CORREO VARCHAR(40) NOT NULL,
CONSTRAINT PK_EMP PRIMARY KEY(CLAVEEMP)
)

--Tabla Trabajo
CREATE TABLE TRABAJO(
CLAVETRAB SMALLINT NOT NULL IDENTITY(1,1),
DESCRIPCION varchar(100),
PRECIO money,
CONSTRAINT PK_TRAB PRIMARY KEY(CLAVETRAB)
)

/*Entidades con llaves foraneas
  y tablas intermedias*/

  --Tabla producto
CREATE TABLE PRODUCTO(
CLAVEPROD SMALLINT NOT NULL IDENTITY(1,1),
DESCRIPCIONPROD VARCHAR(40) NOT NULL,
PRECIOUNIT MONEY NOT NULL,
CANTIDAD FLOAT,		--Flotante porque tal vez venda un pedazo de manguera y son 1.5 mts o a su vez 2 mts, el precio es por metro 
CLAVEPROV SMALLINT NOT NULL,
CONSTRAINT PK_PROD PRIMARY KEY(CLAVEPROD),
CONSTRAINT FK_PROV FOREIGN KEY(CLAVEPROV) REFERENCES PROVEEDOR(CLAVEPROV)
)
--Tabla cliente
CREATE TABLE CLIENTE(
CLAVECLIENTE SMALLINT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(30) NOT NULL,
APELLIDOP VARCHAR(20) NOT NULL, 
APELLIDOM VARCHAR(20) NOT NULL,
NUMTEL BIGINT NOT NULL, 
CORREO VARCHAR(40) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY(CLAVECLIENTE),
)
--Relación Cliente-Trabajo
CREATE TABLE CLIE_TRA(
CLAVECLIENTE SMALLINT NOT NULL,
CLAVETRAB SMALLINT NOT NULL,
CLAVEEMP SMALLINT NOT NULL,
FECHAPEDIDO DATE DEFAULT GetDate(),
FECHATERMINO DATE,
CONSTRAINT PK_CLIE_TRA PRIMARY KEY (CLAVECLIENTE,CLAVETRAB,CLAVEEMP),
CONSTRAINT FK_CLIENTE1 FOREIGN KEY (CLAVECLIENTE) REFERENCES CLIENTE(CLAVECLIENTE),
CONSTRAINT FK_TRAB1 FOREIGN KEY (CLAVETRAB) REFERENCES TRABAJO(CLAVETRAB),
CONSTRAINT FK_EMP1 FOREIGN KEY (CLAVEEMP) REFERENCES EMPLEADO(CLAVEEMP)
)
--Relación Cliente-producto
CREATE TABLE CLIE_PROD(
CLAVECLIENTE SMALLINT NOT NULL IDENTITY(1,1),
CLAVEPROD SMALLINT NOT NULL,
CLAVEEMP SMALLINT NOT NULL,
CANTIDAD TINYINT NOT NULL,
PRECIOUNIT MONEY NOT NULL,
TOTAL MONEY NOT NULL,
FECHACOMPRA DATE DEFAULT GetDate(),
PAGADO BINARY, --BANDERA DE FIAR
CONSTRAINT PK_CLIE_PROD PRIMARY KEY (CLAVECLIENTE,CLAVEPROD,CLAVEEMP),
CONSTRAINT FK_CLIENTE2 FOREIGN KEY (CLAVECLIENTE) REFERENCES CLIENTE(CLAVECLIENTE),
CONSTRAINT FK_PROD2 FOREIGN KEY (CLAVEPROD) REFERENCES PRODUCTO(CLAVEPROD),
CONSTRAINT FK_EMPLEADO2 FOREIGN KEY (CLAVEEMP) REFERENCES EMPLEADO(CLAVEEMP)
)
